# Generated by Django 3.2.4 on 2021-06-25 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=250, validators=[django.core.validators.RegexValidator('\\w')]),
        ),
    ]
