# Generated by Django 3.2.5 on 2021-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythons_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonsuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pythonsuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
