# Generated by Django 3.2.4 on 2021-06-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_notes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notes',
        ),
    ]
